### PR TITLE
Add Release Automation

### PR DESCRIPTION
**Pull request by DTTerastar**
This makes it so making a release will automatically attach the *.exe files built via github actions.

### CODE REVIEW

**Review by robloxrob — APPROVED** [review]
LGTM

**Comment by robloxrob** [comment]
clabot ping

**Comment by robloxrob** [comment]
@DTTerastar 

CLA Signature Action:

Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all read and sign our [Contributor License Agreement](https://roblox.github.io/cla-bot-store/) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:

I have read the CLA Document and I hereby sign the CLA

**Comment by dustin** [comment]
Your CLA bot pings users who aren't contributing to your project.

**Comment by robloxrob** [comment]
My apologies!

**Comment by DTTerastar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by robloxrob** [comment]
Via another merge I think that introduced a merge conflict with go.sum. Would you mind taking a look at that and once that is fixed I can do the merge. @DTTerastar

**Comment by DTTerastar** [comment]
I had pulled in all of 0.20.  I made a new PR (#67) instead of this.

**Pull request closed without merging**
